# Generated by Django 3.0.4 on 2020-03-21 12:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_header', models.CharField(max_length=50)),
                ('note_body', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('notes', django.db.models.manager.Manager()),
            ],
        ),
    ]
