# Generated by Django 3.0.4 on 2020-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
